### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ajwheeler** [ajwheeler/Korg.jl#1]
I mostly manage TODOs by opening new issues, but this list contains many ideas which I haven't taken the time to expand on.

- [ ] Add scattering (via ALI?) https://iopscience.iop.org/article/10.1088/0004-6256/141/6/175/pdf
- [ ] Stancil 1994 provided tables for He2plus in addition to  H2plus bf and ff absorption (which we use).  The data is already, in Korg, we just need to add it as an absorption mechanism.  It should be checked whether this can conceivably ever matter before putting it in.
- [ ] compare D0 vals with those from ATcT (https://atct.anl.gov/Thermochemical%20Data/version%201.118/)
- [ ] Would be good to be able to compute some estimate of the "systematic error" as a function of wavelength
    - [ ] could use the [vald accuracy parameters](https://www.astro.uu.se/valdwiki/VALD3_accuracy)
- [ ] improve package load time.  
- [ ] Would be good to support both generic ABO recipes (given l for upper and lower states) for the sake of parity with turbospectrum.
- [ ] it would be nice to have the tutorial notebook integrated with the docs.  This can be done with Literate.jl, e.g. https://ferrite-fem.github.io/Ferrite.jl/stable/examples/heat_equation/#Introduction
- [ ] H lines should have automatic windowing. See discussion in #140 
- [ ] DataInterpolations now has multivariate cubic interpolation which we might want to lift for Korg. (Likely better to do tis by duplicating the source rather than adding the dependency since it's a bit heavy.) We are currently using multivariate linear interpolation in several places.  It's important to make sure that we don't accidentally end up on the wrong side of the accuracy/speed tradeoff by doing this.
- [ ] Are we using the most up-to-date Stark broadening prescription? See discussion in Korg 2 paper.
- [ ] in [Including all the lines](https://cdnsciencepub.com/doi/10.1139/p10-104), Kurucz mentions depth-dependent microturbulent velocity.  He is discussing opacities for model atmospheres, but I suspect also relevant for synthesis.
- [ ] we should do real convolution of stark and self-broadening profiles for H alpha, beta, and gamma
- [ ] Better default `gamma_rad` estimates.  Can use more data about upper level and `J` when available. For diatomic molecules: http://articles.adsabs.harvard.edu/pdf/1983A%26A...128..291L.
- [ ] we load ionization energies from Barklem and Collet at import time, but it might be sensible to hardcode these.  I think they are very well known and available from NIST.  Don't do this without confirming that they are very well-known.
- [ ] better treatment of autoionizing lines?  They should technically have Fano profiles (and broadening treatment needs a revision, I think).
- [ ] Should I include a Delta gamma_6 fudge factor for non-ABO lines?
- [ ] Zeeman broadening and polarized radiative transfer (e.g. https://arxiv.org/pdf/2303.11241.pdf)
